/*
 * eggmarshalers.h -- custom GObject signal marshaler declarations for the tray plugin.
 *
 * Generated by glib-genmarshal from eggmarshalers.list.
 * Included via egg-marshal.c, which includes eggmarshalers.c.inc.
 *
 * These marshalers are used by EggTrayManager to emit signals with
 * non-standard parameter combinations that the default GLib marshalers
 * do not cover:
 *
 *   _egg_marshal_VOID__OBJECT_OBJECT
 *     Used for signals passing two GObject* arguments (e.g. icon added/removed
 *     with both the tray manager and the icon widget).
 *
 *   _egg_marshal_VOID__OBJECT_STRING_LONG_LONG
 *     Used for signals passing a GObject*, a string, and two longs
 *     (e.g. "message_sent" with widget, message text, id, timeout).
 *
 *   _egg_marshal_VOID__OBJECT_LONG
 *     Used for signals passing a GObject* and a long
 *     (e.g. "message_cancelled" with widget and message id).
 *
 * All marshalers have void return type and accept a standard GClosure
 * invocation header (closure, return_value, n_param_values, param_values,
 * invocation_hint, marshal_data).
 */

#ifndef ___egg_marshal_MARSHAL_H__
#define ___egg_marshal_MARSHAL_H__

#include	<glib-object.h>

G_BEGIN_DECLS

/* VOID:OBJECT,OBJECT (eggmarshalers.list:1) */
extern void _egg_marshal_VOID__OBJECT_OBJECT (GClosure     *closure,
                                              GValue       *return_value,
                                              guint         n_param_values,
                                              const GValue *param_values,
                                              gpointer      invocation_hint,
                                              gpointer      marshal_data);

/* VOID:OBJECT,STRING,LONG,LONG (eggmarshalers.list:2) */
extern void _egg_marshal_VOID__OBJECT_STRING_LONG_LONG (GClosure     *closure,
                                                        GValue       *return_value,
                                                        guint         n_param_values,
                                                        const GValue *param_values,
                                                        gpointer      invocation_hint,
                                                        gpointer      marshal_data);

/* VOID:OBJECT,LONG (eggmarshalers.list:3) */
extern void _egg_marshal_VOID__OBJECT_LONG (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

G_END_DECLS

#endif /* ___egg_marshal_MARSHAL_H__ */
